name: Build Image

on: [push]
jobs:
  build-image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: build image
        run: docker image build -t kompiro/techpitgram4 .